default_platform(:ios)

platform :ios do
  lane :beta do
    # Build file IPA
    build_app(
      workspace: "Runner.xcworkspace",
      configuration: "Release",
      scheme: "Runner",
      silent: true,
      clean: true,
      output_directory: "./build/ios",
      output_name: "Runner",
    )

    # Upload file IPA lên TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      groups: "internal_testers",
      distribute_external: false,
      notify_external_testers: true,
      ipa: "./build/ios/Runner.ipa"
    )
  end
end
