# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    match(
      app_identifier: "vn.dhysolutions.management-spa",
      git_url: "https://github.com/hovanduong/fastlane-certificates-spa-app-customer",
      type: "development",
      git_branch: "main",
      readonly: true,
      force: false
    )
    clean_build_artifacts
    build_app(
      scheme: "Runner",
      archive_path: "./build/Runner.xcarchive",
      export_method: "development",
      configuration: "Release",
      output_directory: "./build/Runner"
    )
    # upload_to_testflight
  end
end
