
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNIFuAgfdp_vuZtPRKRTi2YzqyxMErg0I',
    appId: '1:467887400203:web:26dafdb4940347ced66e0e',
    messagingSenderId: '467887400203',
    projectId: 'spa-product',
    authDomain: 'spa-product.firebaseapp.com',
    storageBucket: 'spa-product.appspot.com',
    measurementId: 'G-05N9C3MGT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpiCIWpY0T_dlzHtM9hJB_l_RYUWRyE9Q',
    appId: '1:467887400203:android:f6ed17176f331382d66e0e',
    messagingSenderId: '467887400203',
    projectId: 'spa-product',
    storageBucket: 'spa-product.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3XzZ6_azth6BgVuN_sZ72QylNg1pwmw',
    appId: '1:467887400203:ios:b664ac9b58daadf8d66e0e',
    messagingSenderId: '467887400203',
    projectId: 'spa-product',
    storageBucket: 'spa-product.appspot.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj3XzZ6_azth6BgVuN_sZ72QylNg1pwmw',
    appId: '1:467887400203:ios:b664ac9b58daadf8d66e0e',
    messagingSenderId: '467887400203',
    projectId: 'spa-product',
    storageBucket: 'spa-product.appspot.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
