// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtenkcp-8PdwNbHfvtwupeuekS7WKaMSA',
    appId: '1:477302719227:web:052b4bd4fe7f41e1ade65e',
    messagingSenderId: '477302719227',
    projectId: 'dating-dev-b76a6',
    authDomain: 'dating-dev-b76a6.firebaseapp.com',
    storageBucket: 'dating-dev-b76a6.appspot.com',
    measurementId: 'G-3KPDHRRM4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV2HU0GLOKUYIAgUHhDnnP4NiNQKKNEQA',
    appId: '1:477302719227:android:59ed6133800781bbade65e',
    messagingSenderId: '477302719227',
    projectId: 'dating-dev-b76a6',
    storageBucket: 'dating-dev-b76a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACt1b52ijHLODIk_rVmWPp5lnC-MP_W1g',
    appId: '1:477302719227:ios:4c140e3e0cbc89a3ade65e',
    messagingSenderId: '477302719227',
    projectId: 'dating-dev-b76a6',
    storageBucket: 'dating-dev-b76a6.appspot.com',
    androidClientId: '477302719227-5udggpd1smlft4c7t0aonr3tfrbkmhuq.apps.googleusercontent.com',
    iosClientId: '477302719227-025ijo01vmljf7m69e48uul667ul8iq6.apps.googleusercontent.com',
    iosBundleId: 'dhy.company.booking.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACt1b52ijHLODIk_rVmWPp5lnC-MP_W1g',
    appId: '1:477302719227:ios:1fefb8ab83825422ade65e',
    messagingSenderId: '477302719227',
    projectId: 'dating-dev-b76a6',
    storageBucket: 'dating-dev-b76a6.appspot.com',
    androidClientId: '477302719227-5udggpd1smlft4c7t0aonr3tfrbkmhuq.apps.googleusercontent.com',
    iosClientId: '477302719227-l2829f2lo15hicupjfg0u2nai4qs3cn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
