# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #

# # Uncomment the line if you want fastlane to automatically update itself
# # update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
default_platform(:android)

platform :android do
  
  desc "Submit a new Build"
  lane :beta do

  #   Dir.chdir "../.." do
  #     # sh("flutter", "build", "appbundle", "--release")
  #     sh("flutter", "build", "apk",)

  #  end
     
    firebase_app_distribution(
        debug: true,
        app: "spadev-64c7e",
        firebase_cli_token: "1//0eYjREv00-98qCgYIARAAGA4SNwF-L9IrtBg85y-IhdWH3vfO18PN8otB1yyEnNxHJC23RBwMwz3X6s4Bgt248j7F5WjGd25XUjQ",
        # apk_path: "../build/app/outputs/flutter-aab/app-release.aab",
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
        groups: "testers"
    )
  end  
end