name: Flutter CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "any"
          channel: "any"

      - name: Clean Code
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      # - name: Run Tests
      #   run: flutter test

      - name: Notify Discord on Failure
        if: failure()
        uses: appleboy/discord-action@latest
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK }}
          message: "CI Failed!"

      - name: Notify Discord on Success
        if: success()
        uses: appleboy/discord-action@latest
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK }}
          message: "CI Passed!"
