name: Flutter CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "any"
          channel: "any"

      - name: Clean Code
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      # - name: Run Tests
      #   run: flutter test
